name: Test and build

on: [push]

jobs:
  build:
    name: Run make test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go 1.22
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build
      run: |
        go build

    - name: Test
      run: |
        make test
